# Generated by Django 5.2 on 2025-04-28 17:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_diary_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='project.lessonschedule'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
