# Generated by Django 5.2 on 2025-04-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_student_studentactivity_task_remove_chatuser_chat_and_more'),
        ('user', '0002_myuser_parent_alter_myuser_grade_alter_myuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_victory', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
        ),
    ]
