# Generated by Django 5.2 on 2025-04-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=223)),
                ('last_name', models.CharField(max_length=223)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=223)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('grade', models.PositiveSmallIntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/user_cover')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('if_used', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
        ),
    ]
