# Generated by Django 5.2 on 2025-04-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_children', to='user.myuser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('admin', 'Админ'), ('teacher', 'Учитель')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
